Demonstrate various data formats for files customization
osbuild/guides pull request #105
Opened 2023-03-08 16:01 UTC by thozza

Demonstrate various data formats for files customization

2023-03-09 08:48 UTC, ondrejbudai requested changes
I wonder if we shouldn't mention just multi-line strings, since the literal string example is actually incorrect and basic strings are obvious...

2023-03-09 08:53 UTC, thozza commented on osbuild-composer/src/blueprint-reference/blueprint-reference.md
> +Note that the `data` property can be specified in any of the ways supported by TOML. Some of them require escaping certain characters and others don't. The following examples are equivalent:
I considered this, but since the documentation will be used also for RHEL docs, I was not sure it it would be OK to link to this there. Thus I decided to specify everything literally here, since it was not too much.

2023-03-09 08:55 UTC, thozza commented on osbuild-composer/src/blueprint-reference/blueprint-reference.md
> +data = """"This is a complicated content"
Of course it does, so OBVIOUS 🤦

2023-03-09 11:28 UTC, supakeen commented on osbuild-composer/src/blueprint-reference/blueprint-reference.md
> +Note that the `data` property can be specified in any of the ways supported by TOML. Some of them require escaping certain characters and others don't. Please refer to the [TOML specification](https:
Just this reference is enough (for me).

2023-03-09 11:35 UTC, thozza commented on osbuild-composer/src/blueprint-reference/blueprint-reference.md
> +Note that the `data` property can be specified in any of the ways supported by TOML. Some of them require escaping certain characters and others don't. Please refer to the [TOML specification](https:
Fair. I'll let others comment as well, but I'm happy to make the change as I don't have a strong preference here...

2023-03-09 11:54 UTC, ondrejbudai reviewed
Looks good, no strong feelings about the examples from my side.

2023-03-09 14:29 UTC, elianerpereira reviewed
I like that you added a link to the TOML specification. This update looks great, @thozza!

2023-03-10 09:09 UTC, thozza commented on osbuild-composer/src/blueprint-reference/blueprint-reference.md
> +Note that the `data` property can be specified in any of the ways supported by TOML. Some of them require escaping certain characters and others don't. Please refer to the [TOML specification](https:
I kept only the link to the spec.

2023-03-10 09:29 UTC, ondrejbudai requested changes

2023-03-10 09:29 UTC, ondrejbudai commented on osbuild-composer/src/blueprint-reference/blueprint-reference.md
> +Note that the `data` property can be specified in any of the ways supported by TOML. Some of them require escaping certain characters and others don't. Please refer to the [TOML specification](https:
Actually, the last sentence needs to be removed.

2023-03-10 10:08 UTC, thozza commented on osbuild-composer/src/blueprint-reference/blueprint-reference.md
> +Note that the `data` property can be specified in any of the ways supported by TOML. Some of them require escaping certain characters and others don't. Please refer to the [TOML specification](https:
🤦

2023-03-10 10:09 UTC, thozza commented on osbuild-composer/src/blueprint-reference/blueprint-reference.md
> +Note that the `data` property can be specified in any of the ways supported by TOML. Some of them require escaping certain characters and others don't. Please refer to the [TOML specification](https:
fixed, thanks!

2023-03-10 10:25 UTC, ondrejbudai approved these changes
Thanks!

2023-03-10 10:25 UTC, merged