changes added to openscap related docs
osbuild/guides pull request #130
Opened 2023-06-21 07:49 UTC by oezeakachi

2023-06-21 08:17 UTC, thozza requested changes
Thanks for your contribution. I added a few comments inline.

2023-06-21 08:17 UTC, thozza commented on src/image-builder-on-premises/uploading-to-aws.md
> +- The `vmimport` role must have read access to the `AWS_BUCKET` please see this guide on how to do so: https://www.msp360.com/resources/blog/how-to-configure-vmimport-role/
nitpick: you could use hyperlinked text to point to the guide, instead of providing the full URL. In addition, I would suggest to link to the official AWS documentation if possible (instead of a "random" blog).

2023-06-21 08:17 UTC, thozza commented on src/image-builder-on-premises/uploading-to-aws.md
> +
I don't find it useful to duplicate basically the same command (one general and one specific to our examples. What is your motivation to add this general syntax example? is the existing example not good enough? Would it be enough to mention in the text leading to the example that it is to build new image with name blueprint name `base-image-with-tmux`?

2023-06-21 08:17 UTC, thozza commented on src/image-builder-on-premises/uploading-to-aws.md
> +where IMAGE_KEY will be the name of your new AMI, once it is uploaded to EC2. Please note this will also kick-off another build in Image Builder so progress can be monitored via the gui.
I'm not sure if this addition is helpful, especially in the AWS-specific section. This is true in general and should be explained (if not done already) somewhere else that a new compose will trigger a new image build. In addition, not sure how relevant is to mention GUI here, since all examples use CLI.

2023-06-21 08:17 UTC, thozza commented on src/image-builder-on-premises/oscap-remediation.md
> +    - Install openscap via this command: dnf install scap-security-guide
nitpick: use preformatted text for commands, so `dnf install scap-security-guide`

2023-06-21 08:17 UTC, thozza commented on src/image-builder-on-premises/oscap-remediation.md
> +    - Use the command oscap info /usr/share/xml/scap/ssg/content/<security_profile>.xml to obtain more information such as the profile id to use
I have the same comment for the file path as above related to the command...

2023-06-21 08:34 UTC, oezeakachi commented on src/image-builder-on-premises/uploading-to-aws.md
> +- The `vmimport` role must have read access to the `AWS_BUCKET` please see this guide on how to do so: https://www.msp360.com/resources/blog/how-to-configure-vmimport-role/
Actually I checked the AWS documentation and they didn't give a clear example of how to create a vminport role, if you prefer I can rewrite the documentation from the blog and give reference to it. (Also I did test the role and fulfils it's purpose of uploading images)

2023-06-21 08:59 UTC, oezeakachi commented on src/image-builder-on-premises/oscap-remediation.md
> +    - Install openscap via this command: dnf install scap-security-guide
I'll amend this

2023-06-21 08:59 UTC, oezeakachi commented on src/image-builder-on-premises/oscap-remediation.md
> +    - Use the command oscap info /usr/share/xml/scap/ssg/content/<security_profile>.xml to obtain more information such as the profile id to use
I'll amend this

2023-06-21 09:05 UTC, thozza commented on src/image-builder-on-premises/uploading-to-aws.md
> +
That's fair. Let's go with you version as the only example in that section.

2023-06-21 09:29 UTC, thozza commented on src/image-builder-on-premises/uploading-to-aws.md
> +- The `vmimport` role must have read access to the `AWS_BUCKET` please see this guide on how to do so: https://www.msp360.com/resources/blog/how-to-configure-vmimport-role/
If documenting this in our documentation would not be too extensive, I would prefer this option. Otherwise, I guess it would be acceptable to link to that blog. My reasoning is just that I expect AWS documentation page to be more persistent.

2023-06-21 10:27 UTC, kingsleyzissou commented on src/image-builder-on-premises/oscap-remediation.md
> +    - Install openscap via this command: dnf install scap-security-guide
We also might want to specify installing `openscap-scanner` with this. Because you need the `scap-security-guide` which is just the content and then `openscap-scanner` provides the `oscap` binary.

2023-06-21 11:31 UTC, thozza commented on src/image-builder-on-premises/oscap-remediation.md
> +    - Install openscap via this command: dnf install scap-security-guide
That should not be necessary, since `openscap-scanner` is pulled in as an RPM dependency of the `cap-security-guide` package. At least on Fedora...

2023-06-21 11:34 UTC, oezeakachi commented on src/image-builder-on-premises/uploading-to-aws.md
> +- The `vmimport` role must have read access to the `AWS_BUCKET` please see this guide on how to do so: https://www.msp360.com/resources/blog/how-to-configure-vmimport-role/
Sorry missed this: I did some digging and found this documentation (https://repost.aws/knowledge-center/import-server-ec2-instance) - Could this suffice as hyperlink replacement

2023-06-21 11:35 UTC, oezeakachi commented on src/image-builder-on-premises/uploading-to-aws.md
> +where IMAGE_KEY will be the name of your new AMI, once it is uploaded to EC2. Please note this will also kick-off another build in Image Builder so progress can be monitored via the gui.
I'll remove this

2023-06-21 11:53 UTC, kingsleyzissou commented on src/image-builder-on-premises/oscap-remediation.md
> +    - Install openscap via this command: dnf install scap-security-guide
Valid point

2023-06-21 12:21 UTC, thozza commented on src/image-builder-on-premises/uploading-to-aws.md
> +- The `vmimport` role must have read access to the `AWS_BUCKET` please see this guide on how to do so: https://www.msp360.com/resources/blog/how-to-configure-vmimport-role/
I'll leave this up to you, since I expect that your contributions are based on your experience when importing the image to AWS. If you find the linked AWS docs sufficient, let's use that.

From a brief look, it seems to be OK with links to additional docs if needed.

2023-06-22 09:14 UTC, thozza reviewed
Thanks for making the changes. I added some more comments.

2023-06-22 09:14 UTC, thozza commented on src/image-builder-on-premises/oscap-remediation.md
> +5) The `profile_id` field accepts both the long and short forms, i.e. `cis` or `xccdf_org.ssgproject.content_profile_cis`.
Please use markdown syntax for ordered lists https://www.markdownguide.org/basic-syntax#ordered-lists

2023-06-22 09:14 UTC, thozza commented on src/image-builder-on-premises/oscap-remediation.md
> +4) Use the command ```oscap info /usr/share/xml/scap/ssg/content/<security_profile>.xml``` to obtain more information such as the profile id to use
IMHO there's no need to use triple quote. You should be able to use just ``` `...` ```

2023-06-22 09:14 UTC, thozza commented on src/image-builder-on-premises/uploading-to-aws.md
> +$ sudo composer-cli compose start <image_name> ami IMAGE_KEY aws-config.toml
You should amend the sentence before this new block (line 26), since it does not make much sense after your changes.

2023-06-22 14:55 UTC, oezeakachi commented on src/image-builder-on-premises/oscap-remediation.md
> +5) The `profile_id` field accepts both the long and short forms, i.e. `cis` or `xccdf_org.ssgproject.content_profile_cis`.
I tried to but for some reason it leaves the preformatted commands looking like normal text. Do you know I can fix this

2023-06-23 11:51 UTC, thozza commented on src/image-builder-on-premises/oscap-remediation.md
> +</ol>
I'm sorry, but I meant just something like:

```md
1. text
2. text
3. text
```
There's no need to use HTML tags. I apologize for not being more specific.

2023-06-23 11:51 UTC, thozza commented on src/image-builder-on-premises/uploading-to-aws.md
> +$ sudo composer-cli compose start <image_name> ami IMAGE_KEY aws-config.toml
Reading this again, this dos not seem relevant. Sorry for the noise.

2023-06-23 11:55 UTC, thozza commented on src/image-builder-on-premises/oscap-remediation.md
> +5) The `profile_id` field accepts both the long and short forms, i.e. `cis` or `xccdf_org.ssgproject.content_profile_cis`.
Weird :thinking: I'll think about it.

2023-06-23 11:55 UTC, thozza commented on src/image-builder-on-premises/oscap-remediation.md
> +</ol>
Please disregard this for now, as I missed you comment above...

2023-06-26 13:29 UTC, thozza commented on src/image-builder-on-premises/oscap-remediation.md
> +## Openscap Example
I just noticed that you used heading with the same level as the original one above, which makes that section empty. I would suggest to not use heading for the example, just a simple text.

2023-06-30 14:34 UTC, thozza reviewed
Changes look good, thanks for your patience. :+1: 

Please squash all commits into a single one and I'll happily approve the PR after that.

2023-07-03 12:26 UTC, ochosi approved these changes
Approved as per https://github.com/osbuild/guides/pull/130#pullrequestreview-1507317982

Thanks, Obi!

2023-07-03 12:26 UTC, merged