Document local_save
osbuild/guides pull request #143
Opened 2023-08-09 23:39 UTC by bcl

And cloudapi local cert setup.

2023-08-10 09:49 UTC, achilleas-k requested changes
Nice work.  A few minor comments in-line.  Also a question about the `local.md` page.

2023-08-10 09:49 UTC, achilleas-k commented on src/developer-guide/projects/osbuild-composer/local.md
> +### Setup Local API Access
Is this a partially written page that was accidentally added, or did you mean to add it and keep it unlinked until it's finished?

2023-08-10 09:49 UTC, achilleas-k commented on src/developer-guide/projects/osbuild-composer/localcloud.md
> +Use `./start-cloudapi simple-guest.json` start the build. You should get a JSON response similar to this:
I'm sure it's obvious, but maybe mention that the json above is the content of the `simple-guest.json` (maybe by just putting the filename above the content).

2023-08-10 09:49 UTC, achilleas-k commented on src/developer-guide/projects/osbuild-composer/localcloud.md
> +re-copy the service file.
A drop-in file created with `systemctl edit osbuild-composer.service` will survive reinstalls, so maybe that would be better advice here.

2023-08-10 10:50 UTC, thozza commented on src/developer-guide/projects/osbuild-composer/localcloud.md
> +re-copy the service file.
+1 for using systemd unit drop-in...

As a side note, one can override units in `/etc/systemd/system/` which will survive reinstall. Nevertheless, drop-in is IMO much better solution, since it will override / extend part of the unit, while still reflecting any updates from the unit installed by RPM.

2023-08-10 13:55 UTC, thozza commented on src/developer-guide/projects/osbuild-composer/localcloud.md
> +Use `./start-cloudapi simple-guest.json` start the build. You should get a JSON response similar to this:
+1

2023-08-10 15:22 UTC, bcl commented on src/developer-guide/projects/osbuild-composer/localcloud.md
> +re-copy the service file.
Oh, nice! I haven't used drop-ins at all so didn't even think of it.

2023-08-10 15:23 UTC, bcl commented on src/developer-guide/projects/osbuild-composer/local.md
> +### Setup Local API Access
oh crud, it was supposed to be removed. I renamed it to localcloud.md

2023-08-11 08:57 UTC, achilleas-k approved these changes

2023-08-11 08:57 UTC, merged