Improve the section about repository management
osbuild/guides pull request #44
Opened 2021-09-09 12:46 UTC by msehnout

See individual commits.

2021-09-09 13:28 UTC, achilleas-k requested changes
Nice!  Thanks for pinging me on this.  I have a couple of suggestions.

2021-09-09 13:28 UTC, achilleas-k commented on osbuild-composer/src/user-guide/managing-repositories.md
> +Based on the system, you want to build an image for, determine the name of a new JSON file:
Superfluous comma
```suggestion
Based on the system you want to build an image for, determine the name of a new JSON file:
```

2021-09-09 13:28 UTC, achilleas-k commented on osbuild-composer/src/user-guide/managing-repositories.md
> +For example, a repository for building a Fedora 33 image running on x86_64, create `/etc/osbuild-composer/repositories/fedora-33.json` with this content:
The sentence fragment between commas doesn't really work.  I think something like the following would   be correct:
```suggestion
For example, for building a Fedora 33 image running on x86_64, create `/etc/osbuild-composer/repositories/fedora-33.json` with this content:
```

2021-09-10 07:37 UTC, msehnout commented
> Nice! Thanks for pinging me on this. I have a couple of suggestions.

Perfect, thanks. I've applied both of your suggestions :-)

2021-09-10 13:19 UTC, achilleas-k approved these changes

2021-09-10 13:19 UTC, merged