Introduce section about building OSTree commits
osbuild/guides pull request #6
Opened 2021-01-27 14:24 UTC by msehnout

2021-01-28 10:00 UTC, gicmo reviewed
Very nice. Thanks for that! A few comments inline.

2021-01-28 10:06 UTC, achilleas-k reviewed
Great guide.  Found a couple of typos :)

2021-01-28 10:06 UTC, achilleas-k commented on osbuild-composer/src/user-guide/building-ostree-images.md
> +* Connect the guest to a virtual netowrk bridge on the host and forward SSH port (22) from the host to the TCP port 2223 on the guest (makes it easier to connect to the host system).
```suggestion
* Connect the guest to a virtual network bridge on the host and forward SSH port (22) from the host to the TCP port 2223 on the guest (makes it easier to connect to the host system).
```

Besides the typo, shouldn't this be the other way around?
We forward the host's 2223 to the guest's 22, to make it easier to connect to the _guest_ (the VM).

2021-01-28 10:06 UTC, achilleas-k commented on osbuild-composer/src/user-guide/building-ostree-images.md
> +Press "Enter", the Anaconda GUI will show up and automatically install the OSTree commit create above.
```suggestion
Press "Enter", the Anaconda GUI will show up and automatically install the OSTree commit created above.
```

2021-01-28 10:31 UTC, msehnout commented on osbuild-composer/src/user-guide/building-ostree-images.md
> +In this guide, a container running Apache httpd will be used as the HTTP server.
I don't get this one 😇

2021-01-28 10:31 UTC, msehnout commented on osbuild-composer/src/user-guide/building-ostree-images.md
> +This section contains a guide for building OSTree commits. As opposed to the "traditional" image types, these commits are not self-sufficient and it is necessary to download Fedora installation ISO.
Yes, much better!

2021-01-28 10:32 UTC, msehnout commented on osbuild-composer/src/user-guide/building-ostree-images.md
> +$ sudo podman run --rm -p 8000:80 ostree
Ah, that would a proper trap for readers!

2021-01-28 10:33 UTC, msehnout commented on osbuild-composer/src/user-guide/building-ostree-images.md
> +* Connect the guest to a virtual netowrk bridge on the host and forward SSH port (22) from the host to the TCP port 2223 on the guest (makes it easier to connect to the host system).
Yes, I got all confused by hosts and guests :-). Thanks!

2021-01-28 10:46 UTC, msehnout commented on osbuild-composer/src/user-guide/building-ostree-images.md
> +As mentioned above, osbuild-composer does not produce self-sufficient images for OSTree. Instead it produces an "OSTree commit" which is a tarball containing filesystem image and metadata files prepa
I've always found this difficult to understand and explain. I'll try to simplify it and skip this sentence altogether.

2021-01-28 11:21 UTC, achilleas-k approved these changes

2021-01-29 11:12 UTC, teg requested changes
This is really nice! Maybe remove/hide or address the two remaining TODOs before merging it though?

2021-01-29 11:39 UTC, msehnout commented
> This is really nice! Maybe remove/hide or address the two remaining TODOs before merging it though?

Yes! Done :-)

2021-01-29 14:15 UTC, msehnout commented
Rendered version: https://www.osbuild.org/guides/pr-12/user-guide/building-ostree-images.html

2021-01-31 15:55 UTC, teg approved these changes
nice!

2021-01-31 15:56 UTC, merged