blueprint-reference: add Ignition config section
osbuild/guides pull request #96
Opened 2022-11-29 17:29 UTC by 7flying

Add info about the new ignition customization.

Please wait until osbuild/osbuild-composer#3161 gets merged to merge this (if approved oc).

2022-12-19 08:55 UTC, 7flying commented
Looking for a review on this, the PR that introduced the changes described here has been merged.

2023-01-12 08:47 UTC, 7flying commented
Updated after some updates made on osbuild/osbuild-composer#3130

2023-01-12 09:23 UTC, runcom commented on osbuild-composer/src/blueprint-reference/blueprint-reference.md
> +in `edge-simplified-installer` ISO images. Check the `r4e`
I think ignition.firstboot is also gonna be for edge-raw-image (I'll confirm by end of day)

2023-01-12 09:30 UTC, 7flying commented on osbuild-composer/src/blueprint-reference/blueprint-reference.md
> +in `edge-simplified-installer` ISO images. Check the `r4e`
Great :+1:

2023-02-09 10:30 UTC, elianerpereira commented on osbuild-composer/src/blueprint-reference/blueprint-reference.md
> +Base64 encoded Ignition file or a URL to where the Ignition file configurarion
Apologies for commenting here, I notice that there is a small typo in "configurarion". Thank you.

2023-02-09 10:55 UTC, runcom commented on osbuild-composer/src/blueprint-reference/blueprint-reference.md
> +url = "http://some-server/configuration.ig"
also Irene, we need to ditch this one as we're not supporting it

2023-02-09 11:13 UTC, elianerpereira commented on osbuild-composer/src/blueprint-reference/blueprint-reference.md
> +The way of specifiying an URL with an ignition file to be fetched at first boot
I also noticed that there is a small typo in "specifiying". Thank you.

2023-02-09 11:58 UTC, 7flying commented on osbuild-composer/src/blueprint-reference/blueprint-reference.md
> +in `edge-simplified-installer` ISO images. Check the `r4e`
Do I have to add the `edge-raw-image`part too? @runcom

2023-02-09 11:59 UTC, 7flying commented on osbuild-composer/src/blueprint-reference/blueprint-reference.md
> +Base64 encoded Ignition file or a URL to where the Ignition file configurarion
Your comments are super welcome!
Nice catch :+1:

2023-02-09 12:02 UTC, runcom commented on osbuild-composer/src/blueprint-reference/blueprint-reference.md
> +in `edge-simplified-installer` ISO images. Check the `r4e`
I think so yeah, raw image just supports firstboot indeed

2023-02-09 12:14 UTC, 7flying commented
@runcom @elianerpereira changes made, let me know if it makes sense

2023-02-09 12:24 UTC, runcom approved these changes

2023-02-09 16:13 UTC, miabbott commented on osbuild-composer/src/blueprint-reference/blueprint-reference.md
> +The `customizations.ignition` section allows to provide
I think this reads a little better as :

> The `customizations.ignition` section allows users to provide

2023-02-09 16:27 UTC, 7flying commented on osbuild-composer/src/blueprint-reference/blueprint-reference.md
> +The blueprint configuration can be done *either* by embedding an ignition
Yep, if fact everywhere else is on capital letters, so that's a slip on my end, nice catch :+1:

2023-02-09 16:29 UTC, 7flying commented
Updated after @miabbott comments.

2023-03-09 10:48 UTC, thozza requested changes
Thanks for the PR. I added a few comments. In addition to that, please do not break lines in the same paragraph and let the MD interpreter which generates the Guides Web page deal with that. IOW, a paragraph should be a single long line.

2023-03-09 10:48 UTC, thozza commented on osbuild-composer/src/blueprint-reference/blueprint-reference.md
> +in `edge-raw-image` and `edge-simplified-installer` ISO images. Check the `r4e`
Would it make sense to specify "RHEL for Edge (r4e)" instead of just "r4e"?

2023-03-09 10:48 UTC, thozza commented on osbuild-composer/src/blueprint-reference/blueprint-reference.md
> +config = "eyJ --- BASE64 STRING TRIMMED --- 19fQo="
I would just specify a valid `base64` string. Ideally some very short and simple configuration.

2023-03-09 10:48 UTC, thozza commented on osbuild-composer/src/blueprint-reference/blueprint-reference.md
> +in `edge-raw-image` and `edge-simplified-installer` ISO images. Check the `r4e`
In addition to that, I would omit the "ISO" from this line. The reason is that the `edge-raw-image` is not an ISO and the sentence make is look as if it was (IMO).

2023-03-09 10:48 UTC, thozza commented on osbuild-composer/src/blueprint-reference/blueprint-reference.md
> +configuration file into the ISO (only available for
I suggest to replace "ISO" with "image".

2023-03-09 11:04 UTC, 7flying commented
Replaced ISO with image in a couple of places, added full base64 working example, changed paragraphs to be single-line paragraphs, expanded the `r4e` acronym

2023-03-09 11:32 UTC, thozza reviewed
Sorry, but I missed one thing in my previous review. Otherwise this looks OK from my PoV

2023-03-09 11:32 UTC, thozza commented on osbuild-composer/src/blueprint-reference/blueprint-reference.md
> +Add a `base64` encoded Ignition configuration in the `config` field. This Ignition configuration will be included in the `edge-simplified-installer` ISO.
Sorry, misses one instance of "ISO" here. I would suggest to also replace it with "image" if that makes sense. My reasoning is that the Ignition customization is applied to the payload installed by the installer, not the installer ISO itself (if I'm not mistaken).

2023-03-09 13:42 UTC, thozza submitted a review, later dismissed
👍

2023-05-08 09:23 UTC, runcom approved these changes

2023-05-11 05:41 UTC, merged

2023-05-11 07:15 UTC, 7flying commented
@supakeen thank you!!