Document new source check_repogpg flag and gpgkeys field.
osbuild/guides pull request #99
Opened 2023-01-23 23:49 UTC by bcl

Documentation for https://github.com/osbuild/osbuild-composer/pull/3230

2023-02-01 11:54 UTC, ochosi requested changes
Overall looks good to me! Just that one sentence is a bit off.

2023-02-01 11:54 UTC, ochosi commented on osbuild-composer/src/user-guide/managing-repositories.md
> +In order to check this signature you need, and you need to tell osbuld-composer
There's a typo and it seems one superfluous 'you need' (or something is missing in the sentence)
```suggestion
In order to check this signature you need, and you need to tell osbuild-composer
```

2023-02-01 16:16 UTC, bcl commented on osbuild-composer/src/user-guide/managing-repositories.md
> +In order to check this signature you need, and you need to tell osbuld-composer
Good catch!

2023-02-02 16:13 UTC, ochosi requested changes

2023-02-02 16:13 UTC, ochosi commented on osbuild-composer/src/user-guide/managing-repositories.md
> +In order to check this signature you need to tell osbuld-composer what gpg key
While @dvdhrm is away, I guess I need to keep an eye out for these ;)

2023-02-02 17:27 UTC, ochosi approved these changes
LGTM!

2023-02-02 17:27 UTC, merged